//para describir que pasa en la aplicacion (se utilizan en el action)
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_PRODUCTS_DOWNLOAD = "START_PRODUCTS_DOWNLOAD";
export const SUCCESS_PRODUCTS_DOWNLOAD = "SUCCESS_PRODUCTS_DOWNLOAD";
export const ERROR_PRODUCTS_DOWNLOAD = "ERROR_PRODUCTS_DOWNLOAD";

export const GET_DELETE_PRODUCT = "GET_DELETE_PRODUCT";
export const SUCCESS_DELETE_PRODUCT = "SUCCESS_DELETE_PRODUCT";
export const ERROR_DELETE_PRODUCT = "ERROR_DELETE_PRODUCT";

export const GET_EDIT_PRODUCT = "GET_EDIT_PRODUCT";
export const START_EDIT_PRODUCT = "START_EDIT_PRODUCT";
export const SUCCESS_EDIT_PRODUCT = "SUCCESS_EDIT_PRODUCT";
export const ERROR_EDIT_PRODUCT = "ERROR_EDIT_PRODUCT";

export const SHOW_ALERT = "SHOW_ALERT"; 
export const HIDE_ALERT = "HIDE_ALERT"; 