//para describir que pasa en la aplicacion (se utilizan en el action)
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_PRODUCTS_DOWNLOAD = "START_PRODUCTS_DOWNLOAD";
export const SUCCESS_PRODUCTS_DOWNLOAD = "SUCCESS_PRODUCTS_DOWNLOAD";
export const ERROR_PRODUCTS_DOWNLOAD = "ERROR_PRODUCTS_DOWNLOAD";
